version: '3.8'
services:
  chess-tourney-db:
    image: mongo:latest
    ports:
      - '27019:27017'

  chess-tourney-nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    network_mode: host
      